// <autogenerated />

using System;
using System.Diagnostics.CodeAnalysis;
using System.Linq;
using Microsoft.Extensions.FileSystemGlobbing;
using Microsoft.Extensions.FileSystemGlobbing.Abstractions;

#pragma warning disable

#nullable disable

// ReSharper disable once CheckNamespace
namespace Pathy
{
#if PATHY_PUBLIC
    public static class ChainablePathExtensions
#else
    [global::Microsoft.CodeAnalysis.Embedded]
    internal static class ChainablePathExtensions
#endif
    {
        /// <summary>
        /// Matches files in the specified directory or subdirectories according to the provided glob pattern
        /// and returns them as an array of <see cref="ChainablePath"/> objects.
        /// </summary>
        /// <remarks>
        /// See also <seealso href="https://learn.microsoft.com/en-us/dotnet/core/extensions/file-globbing"/>
        /// </remarks>
        /// <param name="path">The base directory path to start the glob search from.</param>
        /// <param name="globPattern">The glob pattern used to match file paths, e.g. **/*.md or dir/**/*</param>
        public static ChainablePath[] GlobFiles(this ChainablePath path, string globPattern)
        {
            Matcher matcher = new(StringComparison.OrdinalIgnoreCase);
            matcher.AddInclude(globPattern);

            return matcher
                .Execute(new DirectoryInfoWrapper(path.ToDirectoryInfo()))
                .Files
                .Select(file => ChainablePath.From(path / file.Path))
                .ToArray();
        }
    }
}

// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
namespace Microsoft.CodeAnalysis
{
    /// <summary>
    /// A special attribute recognized by Roslyn, that marks a type as "embedded", meaning it won't ever be visible from other assemblies.
    /// </summary>
    [AttributeUsage(AttributeTargets.All)]
    [ExcludeFromCodeCoverage]
    internal sealed class EmbeddedAttribute : Attribute
    {
    }
}
