// <autogenerated />

using System;
using System.ComponentModel;
using System.Globalization;

#pragma warning disable

namespace Pathy
{
    /// <summary>
    /// Allows <see cref="ChainablePath"/> to be converted to and from its <see cref="string"/> representation,
    /// so it can be used for binding configuration values (e.g. <c>appsettings.json</c>), command-line arguments
    /// or MSBuild properties through the standard <see cref="TypeConverter"/> infrastructure.
    /// </summary>
#if PATHY_PUBLIC
    public sealed class ChainablePathTypeConverter : TypeConverter
#else
    [global::Microsoft.CodeAnalysis.Embedded]
    [global::System.Diagnostics.DebuggerNonUserCode]
    internal sealed class ChainablePathTypeConverter : TypeConverter
#endif
    {
        public override bool CanConvertFrom(ITypeDescriptorContext? context, Type sourceType)
        {
            return sourceType == typeof(string) || base.CanConvertFrom(context, sourceType);
        }

        public override object? ConvertFrom(ITypeDescriptorContext? context, CultureInfo? culture, object value)
        {
            if (value is string stringValue)
            {
                return ChainablePath.From(stringValue);
            }

            return base.ConvertFrom(context, culture, value);
        }

        public override bool CanConvertTo(ITypeDescriptorContext? context, Type? destinationType)
        {
            return destinationType == typeof(string) || base.CanConvertTo(context, destinationType);
        }

        public override object? ConvertTo(ITypeDescriptorContext? context, CultureInfo? culture, object? value,
            Type destinationType)
        {
            if (destinationType == typeof(string) && value is ChainablePath chainablePath)
            {
                return chainablePath.ToString();
            }

            return base.ConvertTo(context, culture, value, destinationType);
        }
    }
}
