// <autogenerated />

#pragma warning disable

// This converter is opt-in only. System.Text.Json is not available (out of the box) on every framework this
// source-only package targets (notably .NET Framework 4.7 without an extra package), so it must never be
// referenced unconditionally from a file that gets compiled directly into every consuming project. If you want
// to serialize a ChainablePath with System.Text.Json, define the PATHY_SYSTEM_TEXT_JSON compilation symbol in
// your own project (and add a reference to System.Text.Json if your target framework doesn't ship it already).
#if PATHY_SYSTEM_TEXT_JSON
using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Pathy
{
    /// <summary>
    /// Converts a <see cref="ChainablePath"/> to and from its <see cref="string"/> representation when
    /// serializing with <c>System.Text.Json</c>.
    /// </summary>
    /// <remarks>
    /// A serialized path is nothing more than the platform-specific string it wraps. Round-tripping a
    /// Windows-style path (e.g. <c>C:\projects\app</c>) on Linux, or a Unix-style path on Windows, is the
    /// consumer's responsibility; this converter performs no platform translation.
    /// </remarks>
#if PATHY_PUBLIC
    public sealed class ChainablePathJsonConverter : JsonConverter<ChainablePath>
#else
    [global::Microsoft.CodeAnalysis.Embedded]
    [global::System.Diagnostics.DebuggerNonUserCode]
    internal sealed class ChainablePathJsonConverter : JsonConverter<ChainablePath>
#endif
    {
        public override ChainablePath Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string? value = reader.GetString();

            return value is null ? ChainablePath.Empty : ChainablePath.From(value);
        }

        public override void Write(Utf8JsonWriter writer, ChainablePath value, JsonSerializerOptions options)
        {
            writer.WriteStringValue(value.ToString());
        }
    }
}
#endif
