// <autogenerated />

using System;
using System.IO;

#pragma warning disable

#nullable disable

namespace Pathy;

public class ChainablePath
{
    private readonly string path;

    public ChainablePath(string path)
    {
        if (!Path.IsPathRooted(path))
        {
            throw new ArgumentException($"Path \"{path}\" is not an absolute path", nameof(path));
        }

        this.path = path;
    }

    public static ChainablePath From(string path)
    {
        return new ChainablePath(path);
    }

    public string DirectoryName => Path.GetDirectoryName(path);
}
